# create-desktop-shortcut.ps1 - put a clickable entry for the Web UI on the desktop.
#
# The shortcut targets wscript.exe + open-webui-hidden.vbs rather than the URL directly,
# so a double-click also STARTS the service when it is not running. A bare .url shortcut
# would just show a connection error in that case.
#
# Generated by a script on purpose: a .lnk hardcodes an absolute target path, so it is
# not portable between machines. Re-run this on any machine that needs the entry.
$ErrorActionPreference = 'Stop'

$Base      = 'T:\wx4win\wechat-toolkit\autostart'
$Launcher  = Join-Path $Base 'open-webui-hidden.vbs'
$Name      = '微信记录查看器.lnk'

# The desktop really lives at T:\DeskTop on this machine, not in the user profile.
$DesktopCandidates = @('T:\DeskTop', (Join-Path $env:USERPROFILE 'Desktop'))
$Desktop = $DesktopCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $Desktop) { throw 'no desktop folder found' }

if (-not (Test-Path $Launcher)) { throw "launcher not found: $Launcher" }

$linkPath = Join-Path $Desktop $Name

$shell = New-Object -ComObject WScript.Shell
$lnk = $shell.CreateShortcut($linkPath)
$lnk.TargetPath       = Join-Path $env:SystemRoot 'System32\wscript.exe'
$lnk.Arguments        = '"' + $Launcher + '"'
$lnk.WorkingDirectory = $Base
$lnk.IconLocation     = (Join-Path $env:SystemRoot 'System32\shell32.dll') + ',14'
$lnk.Description      = '打开微信聊天记录查看器（会自动启动本地服务）'
$lnk.Save()

# Read it back: Save() succeeding does not prove the path resolved.
$shell2 = New-Object -ComObject WScript.Shell
$check = $shell2.CreateShortcut($linkPath)
Write-Host "created : $linkPath"
Write-Host "target  : $($check.TargetPath)"
Write-Host "args    : $($check.Arguments)"
Write-Host "workdir : $($check.WorkingDirectory)"
Write-Host "launcher exists: $(Test-Path $Launcher)"
